#class0701 $\ 用于精确控制空白，\ 用于通用续行（自动插入空格）。
var=hello$\
world
var2=hello\
world

class0701:
	@echo $(var)
	@echo $(var2)

# class0702
include ./inc/makefile.mk
.PHONY: class0702
class0702:
	@echo $(class0702var2)